apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: external-mysql-operator
  name: external-mysql-operator-account
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: external-mysql-operator-account
rules:
  - apiGroups:
      - mysql.getresponse.com
    resources:
      - instances
      - databases
      - users
    verbs: ["*"]
  - apiGroups:
      - ""
    resources:
      - events
      - services
      - secrets
      - configmaps
    verbs: ["*"]
  - apiGroups:
      - batch
    resources:
      - jobs
      - jobs/status
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: external-mysql-operator-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-mysql-operator-account
subjects:
- kind: ServiceAccount
  name: external-mysql-operator-account
  namespace: external-mysql-operator