apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  namespace: external-mysql-operator
  name: databases.mysql.getresponse.com
spec:
  scope: Namespaced
  group: mysql.getresponse.com
  names:
    kind: database
    plural: databases
    singular: database
    shortNames:
      - databases
      - database
      - dbs
      - db
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                instance:
                  type: string
                dropOnDelete:
                  type: boolean
                users:
                  type: array
                  items:
                    type: object
                    properties:
                      username:
                        type: string
                      password:
                        type: string
                      allowedHosts:
                        type: string
                      tables:
                        type: array
                        items:
                          type: string
                      privileges:
                        type: array
                        items:
                          type: string
                    required:
                    - username
                    - allowedHosts
                    - tables
                    - privileges
                initDb:
                  type: object
                  properties:
                    initDbScript:
                      type: string
                    initDbImage:
                      type: string
                  required:
                  - initDbScript
                  - initDbImage
              required:
              - instance
              - dropOnDelete