apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  namespace: external-mysql-operator
  name: instances.mysql.getresponse.com
spec:
  scope: Namespaced
  group: mysql.getresponse.com
  names:
    kind: instance
    plural: instances
    singular: instance
    shortNames:
      - instances
      - instance
      - inst
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                address:
                  type: string
                port:
                  type: integer
                secretName:
                  type: string
              required:
              - address
              - port
              - secretName